# Generated by Django 4.2 on 2024-01-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialmedia_remove_userinfo_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
