# Generated by Django 4.2.1 on 2023-10-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(default='do dodania po migracji', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='name_pl',
            field=models.CharField(default='do dodania po migracji', max_length=100),
            preserve_default=False,
        ),
    ]
