# Generated by Django 4.2.1 on 2023-10-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_category_name_pl_session_name_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='main_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
