# Generated by Django 4.2 on 2024-01-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_alter_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.session'),
        ),
    ]
